// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Js_json from "@rescript/runtime/lib/es6/Js_json.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function generateCharsetCombinations(charset, minLength, maxLength) {
  if (charset.length === 0) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidCharset",
        _0: "Charset cannot be empty"
      }
    };
  }
  if (minLength < 0 || maxLength < minLength) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidRange",
        _0: "Invalid length range"
      }
    };
  }
  let generateForLength = (chars, length) => {
    if (length === 0) {
      return [""];
    }
    let shorter = generateForLength(chars, length - 1 | 0);
    return Belt_Array.flatMap(chars, char => Belt_Array.map(shorter, suffix => char + suffix));
  };
  let charArray = charset.split("");
  let allPatterns = Belt_Array.flatMap(Belt_Array.range(minLength, maxLength), len => generateForLength(charArray, len));
  return {
    TAG: "Ok",
    _0: allPatterns
  };
}

function generateSequential(start, end) {
  if (start > end) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidRange",
        _0: "Start must be <= end"
      }
    };
  }
  let numbers = Belt_Array.range(start, end);
  let patterns = Belt_Array.map(numbers, n => n.toString());
  return {
    TAG: "Ok",
    _0: patterns
  };
}

function applyMutations(word, level) {
  let capitalize = s => {
    let first = s[0];
    if (first !== undefined) {
      return first.toUpperCase() + s.slice(1, s.length);
    } else {
      return s;
    }
  };
  let leetSpeak = s => s.replace(/a/g, "4").replace(/e/g, "3").replace(/i/g, "1").replace(/o/g, "0").replace(/s/g, "5").replace(/t/g, "7");
  switch (level) {
    case "Minimal" :
      return [
        word,
        capitalize(word)
      ];
    case "Standard" :
      return [
        word,
        capitalize(word),
        word + "123",
        word + "!",
        word + "2024",
        word + "2025",
        leetSpeak(word)
      ];
    case "Aggressive" :
      return Belt_Array.concat([
        word,
        capitalize(word),
        word.toUpperCase(),
        word + "123",
        word + "!",
        word + "?",
        word + "2024",
        word + "2025",
        "!" + word,
        leetSpeak(word)
      ], ["".concat(...Belt_Array.reverse(word.split("")))]);
  }
}

function processWordlist(words, level) {
  if (words.length === 0) {
    return {
      TAG: "Error",
      _0: "EmptyWordlist"
    };
  }
  let mutated = Belt_Array.flatMap(words, word => applyMutations(word, level));
  return {
    TAG: "Ok",
    _0: mutated
  };
}

function estimateTotal(patternType) {
  switch (patternType.TAG) {
    case "Charset" :
      let base = patternType._0.length;
      let _start = patternType._1;
      let end = patternType._2;
      let _acc = 0;
      while (true) {
        let acc = _acc;
        let start = _start;
        if (start > end) {
          return acc;
        }
        _acc = acc + (Math.pow(base, start) | 0) | 0;
        _start = start + 1 | 0;
        continue;
      };
    case "Sequential" :
      return (patternType._1 - patternType._0 | 0) + 1 | 0;
    case "Wordlist" :
      return patternType._0.length;
    case "Custom" :
      return patternType._0().length;
  }
}

let commonPasswords = [
  "password",
  "123456",
  "123456789",
  "12345678",
  "12345",
  "qwerty",
  "abc123",
  "password123",
  "admin",
  "letmein",
  "welcome",
  "monkey",
  "dragon",
  "master"
];

function generateForErlang(patternType, config) {
  switch (patternType) {
    case "charset" :
      let charset = Belt_Option.getWithDefault(Js_json.decodeString(Belt_Option.getExn(Js_dict.get(Belt_Option.getExn(Js_json.decodeObject(config)), "charset"))), "");
      let minLen = Belt_Option.getWithDefault(Js_json.decodeNumber(Belt_Option.getExn(Js_dict.get(Belt_Option.getExn(Js_json.decodeObject(config)), "min_length"))), 1.0) | 0;
      let maxLen = Belt_Option.getWithDefault(Js_json.decodeNumber(Belt_Option.getExn(Js_dict.get(Belt_Option.getExn(Js_json.decodeObject(config)), "max_length"))), 4.0) | 0;
      let patterns = generateCharsetCombinations(charset, minLen, maxLen);
      if (patterns.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: Belt_Option.getWithDefault(JSON.stringify(patterns._0), "[]")
        };
      }
      let msg = patterns._0;
      if (typeof msg !== "object") {
        return {
          TAG: "Error",
          _0: "Unknown error"
        };
      } else if (msg.TAG === "InvalidCharset") {
        return {
          TAG: "Error",
          _0: "Invalid charset: " + msg._0
        };
      } else {
        return {
          TAG: "Error",
          _0: "Invalid range: " + msg._0
        };
      }
    case "common" :
      return {
        TAG: "Ok",
        _0: Belt_Option.getWithDefault(JSON.stringify(commonPasswords), "[]")
      };
    case "sequential" :
      let start = Belt_Option.getWithDefault(Js_json.decodeNumber(Belt_Option.getExn(Js_dict.get(Belt_Option.getExn(Js_json.decodeObject(config)), "start"))), 0.0) | 0;
      let end = Belt_Option.getWithDefault(Js_json.decodeNumber(Belt_Option.getExn(Js_dict.get(Belt_Option.getExn(Js_json.decodeObject(config)), "end"))), 100.0) | 0;
      let patterns$1 = generateSequential(start, end);
      if (patterns$1.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: Belt_Option.getWithDefault(JSON.stringify(patterns$1._0), "[]")
        };
      }
      let msg$1 = patterns$1._0;
      if (typeof msg$1 !== "object" || msg$1.TAG === "InvalidCharset") {
        return {
          TAG: "Error",
          _0: "Unknown error"
        };
      } else {
        return {
          TAG: "Error",
          _0: "Invalid range: " + msg$1._0
        };
      }
    default:
      return {
        TAG: "Error",
        _0: "Unknown pattern type: " + patternType
      };
  }
}

function validatePattern(pattern, minLength, maxLength) {
  let len = pattern.length;
  if (len >= minLength) {
    return len <= maxLength;
  } else {
    return false;
  }
}

function calculateStats(patterns) {
  let total = patterns.length;
  if (total === 0) {
    return {
      totalPatterns: 0,
      minLength: 0,
      maxLength: 0,
      averageLength: 0.0
    };
  }
  let lengths = Belt_Array.map(patterns, prim => prim.length);
  let sum = Belt_Array.reduce(lengths, 0, (acc, len) => acc + len | 0);
  let min = Belt_Array.reduce(lengths, 2147483647, (acc, len) => Math.min(acc, len));
  let max = Belt_Array.reduce(lengths, 0, (acc, len) => Math.max(acc, len));
  return {
    totalPatterns: total,
    minLength: min,
    maxLength: max,
    averageLength: sum / total
  };
}

export {
  generateCharsetCombinations,
  generateSequential,
  applyMutations,
  processWordlist,
  estimateTotal,
  commonPasswords,
  generateForErlang,
  validatePattern,
  calculateStats,
}
/* No side effect */
